name: UI Tests

on:
    workflow_dispatch:

jobs:
  test-chrome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - run: pip install -r requirements.txt

      - name: Run UI tests (Chrome)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EXISTING_USER_EMAIL: ${{ secrets.EXISTING_USER_EMAIL }}
          EXISTING_USER_PASSWORD: ${{ secrets.EXISTING_USER_PASSWORD }}
      - run: pytest tests/test_login.py --browser=Chrome --headless